# Generated by Django 4.2.5 on 2023-09-08 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='user/profile_image/', verbose_name='аватарка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль Пользователя',
                'verbose_name_plural': 'Профиль Пользователей',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Название поста')),
                ('description', models.TextField(verbose_name='Oписание поста')),
                ('image', models.ImageField(upload_to='post_image/', verbose_name='фото публикации')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата пупликации поста')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.profileuser', verbose_name='Имя пользователь')),
            ],
            options={
                'verbose_name': 'Посты',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
